[project]
authors = ["Timur Seitosmanov <timur.seitosmanov@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mlfls-hw"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<4"
jupyter = ">=1.1.1,<2"
pip = ">=24.2,<25"
pandas = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.5.2,<2"
matplotlib = ">=3.9.2,<4"
tqdm = ">=4.67.0,<5"
xgboost = ">=2.1.2,<3"
graphviz = ">=12.0.0,<13"
python-graphviz = ">=0.20.3,<0.21"
dtreeviz = ">=2.2.2,<3"
